# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'HMPFirebase' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
