# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Hampi' do
  use_frameworks!
end

target 'HMPFirebaseKit' do
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
